// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CrewKickoffCrewKickoffPostData, CrewKickoffCrewKickoffPostErrors, CrewKickoffCrewKickoffPostResponses, GetCustomTypeSchemasSchemasGetData, GetCustomTypeSchemasSchemasGetResponses, GetPreDefinedTasksTasksPreDefinedGetData, GetPreDefinedTasksTasksPreDefinedGetResponses, GetRequiredInputsCrewCrewIdRequiredInputsGetData, GetRequiredInputsCrewCrewIdRequiredInputsGetErrors, GetRequiredInputsCrewCrewIdRequiredInputsGetResponses, SystemCheckStatusHealthGetData, SystemCheckStatusHealthGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * System Check
 */
export const systemCheckStatusHealthGet = <ThrowOnError extends boolean = false>(options?: Options<SystemCheckStatusHealthGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<SystemCheckStatusHealthGetResponses, unknown, ThrowOnError>({
        url: '/status/health',
        ...options
    });
};

/**
 * Get Required Inputs
 *
 * Get required inputs for a crew based on its tasks and flow dependencies.
 */
export const getRequiredInputsCrewCrewIdRequiredInputsGet = <ThrowOnError extends boolean = false>(options: Options<GetRequiredInputsCrewCrewIdRequiredInputsGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetRequiredInputsCrewCrewIdRequiredInputsGetResponses, GetRequiredInputsCrewCrewIdRequiredInputsGetErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/crew/{crew_id}/required-inputs',
        ...options
    });
};

/**
 * Crew Kickoff
 *
 * Kick off a crew run. Only crew owners can kick off their crews.
 */
export const crewKickoffCrewKickoffPost = <ThrowOnError extends boolean = false>(options: Options<CrewKickoffCrewKickoffPostData, ThrowOnError>) => {
    return (options.client ?? client).post<CrewKickoffCrewKickoffPostResponses, CrewKickoffCrewKickoffPostErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/crew/kickoff',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Pre Defined Tasks
 *
 * Get all pre-defined tasks with key, name, and task_description.
 */
export const getPreDefinedTasksTasksPreDefinedGet = <ThrowOnError extends boolean = false>(options?: Options<GetPreDefinedTasksTasksPreDefinedGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetPreDefinedTasksTasksPreDefinedGetResponses, unknown, ThrowOnError>({
        url: '/tasks/pre-defined',
        ...options
    });
};

/**
 * Get Custom Type Schemas
 *
 * Exposes custom types in OpenAPI schema for client generation. Returns empty object. This endpoint ensures all custom types (MarketingResearch, ContentStrategy, SocialMediaSchedule, OrshotSchemaField, AllowedTemplateId, OrshotDataType) appear in the OpenAPI schema so tools like openapi-ts can generate TypeScript types.
 */
export const getCustomTypeSchemasSchemasGet = <ThrowOnError extends boolean = false>(options?: Options<GetCustomTypeSchemasSchemasGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetCustomTypeSchemasSchemasGetResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/schemas/',
        ...options
    });
};
