// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8001' | (string & {});
};

/**
 * AllowedTemplateId
 *
 * Registry of supported Orshot Templates.
 * The frontend uses this to render a dropdown.
 */
export type AllowedTemplateId = 1201;

/**
 * ContentStrategy
 *
 * Represents a content strategy plan, typically stored as markdown content.
 *
 * Contains structured content plan with:
 * - Executive summary
 * - Calendar overview with theme/concept, objective, and posting cadence
 * - Phase-based strategy (per month, week, or day)
 */
export type ContentStrategy = {
    /**
     * Content
     *
     * Markdown content of the content strategy
     */
    content: string;
    /**
     * Metadata
     *
     * Optional metadata about the strategy
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * CrewRun
 */
export type CrewRun = {
    /**
     * Id
     */
    id: string;
    /**
     * Crew Id
     */
    crew_id: string;
};

/**
 * CrewRunCreateRequest
 */
export type CrewRunCreateRequest = {
    /**
     * Crew Id
     */
    crew_id: string;
    /**
     * Inputs
     */
    inputs?: {
        [key: string]: unknown;
    } | null;
};

/**
 * CustomTypesResponse
 *
 * Response model exposing all custom types for OpenAPI schema generation.
 *
 * This model is used solely to ensure custom types appear in the OpenAPI schema
 * so that client generation tools (e.g., openapi-ts) can generate TypeScript types.
 * All fields are optional and default to None since this is only for schema exposure.
 */
export type CustomTypesResponse = {
    /**
     * MarketingResearch type schema reference
     */
    marketing_research?: MarketingResearch | null;
    /**
     * ContentStrategy type schema reference
     */
    content_strategy?: ContentStrategy | null;
    /**
     * SocialMediaSchedule type schema reference
     */
    social_media_schedule?: SocialMediaSchedule | null;
    /**
     * OrshotSchemaField type schema reference
     */
    orshot_schema_field?: OrshotSchemaField | null;
    /**
     * AllowedTemplateId enum schema reference
     */
    allowed_template_id?: AllowedTemplateId | null;
    /**
     * OrshotDataType enum schema reference
     */
    orshot_data_type?: OrshotDataType | null;
};

export type FieldTypeInfo = {
    [key: string]: unknown;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MarketingResearch
 *
 * Represents marketing research data, typically stored as markdown content.
 *
 * Contains structured research report with sections like:
 * - Executive summary
 * - Competitive landscape
 * - Emerging trends
 * - Successful examples/references
 * - Recommendations
 * - References
 */
export type MarketingResearch = {
    /**
     * Content
     *
     * Markdown content of the marketing research report
     */
    content: string;
    /**
     * Metadata
     *
     * Optional metadata about the research
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * OrshotDataType
 */
export type OrshotDataType = 'TEXT' | 'IMAGE';

/**
 * OrshotSchemaField
 *
 * Represents a single configurable field in an Orshot Template.
 * User inputs a list of these objects to define the 'rules' for the template.
 */
export type OrshotSchemaField = {
    /**
     * Field
     *
     * The exact parameter key to modify in the Orshot template (e.g., 'headline', 'background_image')
     */
    field: string;
    /**
     * The data type of this field: 'TEXT' or 'IMAGE'
     */
    dataType: OrshotDataType;
    /**
     * Description
     *
     * Contextual description of the field (e.g., 'Main title, max 20 chars', 'Product shot in portrait mode')
     */
    description: string;
};

/**
 * RequiredInputField
 *
 * Represents a single required input field.
 */
export type RequiredInputField = {
    /**
     * Field Name
     *
     * Name of the field
     */
    field_name: string;
    /**
     * Type information for this field
     */
    type_info: FieldTypeInfo;
    /**
     * Field Kind
     *
     * Field kind: 'context' or 'data'
     */
    field_kind: string;
    /**
     * Required
     *
     * Whether this field is required (cannot be left blank)
     */
    required?: boolean;
    /**
     * Placeholder
     *
     * Placeholder text for the input field
     */
    placeholder?: string | null;
};

/**
 * RequiredInputsResponse
 *
 * Response model for required inputs endpoint.
 */
export type RequiredInputsResponse = {
    /**
     * Fields
     *
     * List of required input fields
     */
    fields: Array<RequiredInputField>;
};

/**
 * SocialMediaSchedule
 *
 * Represents a social media posting schedule, typically stored as markdown or structured data.
 *
 * Contains a detailed schedule with:
 * - Post dates and times
 * - Content descriptions
 * - Content types (posts, stories, reels)
 * - Objectives and key messages
 */
export type SocialMediaSchedule = {
    /**
     * Content
     *
     * Markdown or structured content of the social media schedule
     */
    content: string;
    /**
     * Metadata
     *
     * Optional metadata about the schedule
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * TaskInfo
 *
 * Task information exposed to the frontend.
 */
export type TaskInfo = {
    /**
     * Key
     */
    key: string;
    /**
     * Name
     */
    name: string;
    /**
     * Task Description
     */
    task_description: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type SystemCheckStatusHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status/health';
};

export type SystemCheckStatusHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRequiredInputsCrewCrewIdRequiredInputsGetData = {
    body?: never;
    path: {
        /**
         * Crew Id
         */
        crew_id: string;
    };
    query?: never;
    url: '/crew/{crew_id}/required-inputs';
};

export type GetRequiredInputsCrewCrewIdRequiredInputsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRequiredInputsCrewCrewIdRequiredInputsGetError = GetRequiredInputsCrewCrewIdRequiredInputsGetErrors[keyof GetRequiredInputsCrewCrewIdRequiredInputsGetErrors];

export type GetRequiredInputsCrewCrewIdRequiredInputsGetResponses = {
    /**
     * Successful Response
     */
    200: RequiredInputsResponse;
};

export type GetRequiredInputsCrewCrewIdRequiredInputsGetResponse = GetRequiredInputsCrewCrewIdRequiredInputsGetResponses[keyof GetRequiredInputsCrewCrewIdRequiredInputsGetResponses];

export type CrewKickoffCrewKickoffPostData = {
    body: CrewRunCreateRequest;
    path?: never;
    query?: never;
    url: '/crew/kickoff';
};

export type CrewKickoffCrewKickoffPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CrewKickoffCrewKickoffPostError = CrewKickoffCrewKickoffPostErrors[keyof CrewKickoffCrewKickoffPostErrors];

export type CrewKickoffCrewKickoffPostResponses = {
    /**
     * Successful Response
     */
    201: CrewRun;
};

export type CrewKickoffCrewKickoffPostResponse = CrewKickoffCrewKickoffPostResponses[keyof CrewKickoffCrewKickoffPostResponses];

export type GetPreDefinedTasksTasksPreDefinedGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tasks/pre-defined';
};

export type GetPreDefinedTasksTasksPreDefinedGetResponses = {
    /**
     * Response Get Pre Defined Tasks Tasks Pre Defined Get
     *
     * Successful Response
     */
    200: Array<TaskInfo>;
};

export type GetPreDefinedTasksTasksPreDefinedGetResponse = GetPreDefinedTasksTasksPreDefinedGetResponses[keyof GetPreDefinedTasksTasksPreDefinedGetResponses];

export type GetCustomTypeSchemasSchemasGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/schemas/';
};

export type GetCustomTypeSchemasSchemasGetResponses = {
    /**
     * Successful Response
     */
    200: CustomTypesResponse;
};

export type GetCustomTypeSchemasSchemasGetResponse = GetCustomTypeSchemasSchemasGetResponses[keyof GetCustomTypeSchemasSchemasGetResponses];
