// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8001' | (string & {});
};

/**
 * AllowedTemplateId
 *
 * Registry of supported Orshot Templates.
 * The frontend uses this to render a dropdown.
 */
export type AllowedTemplateId = 1201 | 1909;

/**
 * ContentStrategy
 *
 * Complete content strategy output.
 *
 * - `content`: Human-readable markdown summary
 * - `global_settings`: Tone, voice, brand alignment, audience considerations
 * - `phases`: Structured, agent-parsable strategy blocks (no dates!)
 * - `metadata`: Version, timestamps, etc.
 */
export type ContentStrategy = {
    /**
     * Content
     *
     * Full content strategy rendered as markdown
     */
    content: string;
    /**
     * Global Settings
     *
     * High-level settings: tone, voice, brand alignment, messaging principles, content pillars
     */
    global_settings: {
        [key: string]: unknown;
    };
    /**
     * Phases
     *
     * List of strategic phases that define themes, cadence, and objectives without assigning dates
     */
    phases: Array<StrategyPhase>;
};

/**
 * CrewRun
 */
export type CrewRun = {
    /**
     * Id
     */
    id: string;
    /**
     * Crew Id
     */
    crew_id: string;
};

/**
 * CrewRunCreateRequest
 */
export type CrewRunCreateRequest = {
    /**
     * Crew Id
     */
    crew_id: string;
    /**
     * Inputs
     */
    inputs?: {
        [key: string]: unknown;
    } | null;
};

/**
 * CustomTypesResponse
 *
 * Response model exposing all custom types for OpenAPI schema generation.
 *
 * This model is used solely to ensure custom types appear in the OpenAPI schema
 * so that client generation tools (e.g., openapi-ts) can generate TypeScript types.
 * All fields are optional and default to None since this is only for schema exposure.
 */
export type CustomTypesResponse = {
    /**
     * MarketingResearchReport type schema reference
     */
    marketing_research_report?: MarketingResearchReport | null;
    /**
     * StrategyPhase type schema reference
     */
    strategy_phase?: StrategyPhase | null;
    /**
     * ContentStrategy type schema reference
     */
    content_strategy?: ContentStrategy | null;
    /**
     * ScheduleItem type schema reference
     */
    schedule_item?: ScheduleItem | null;
    /**
     * SocialMediaSchedule type schema reference
     */
    social_media_schedule?: SocialMediaSchedule | null;
    /**
     * OrshotSchemaField type schema reference
     */
    orshot_schema_field?: OrshotSchemaField | null;
    /**
     * AllowedTemplateId enum schema reference
     */
    allowed_template_id?: AllowedTemplateId | null;
    /**
     * OrshotDataType enum schema reference
     */
    orshot_data_type?: OrshotDataType | null;
};

export type FieldTypeInfo = {
    [key: string]: unknown;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MarketingResearchReport
 *
 * Structured representation of the marketing‑research markdown report.
 *
 * The task’s `expected_output` asks for a markdown document that contains:
 *
 * • Executive summary
 * • Competitive landscape
 * • Emerging trends
 * • Successful examples / references
 * • Recommendations
 * • References
 *
 * Each section is stored as a separate string so the workflow can either:
 * – render the whole markdown (`report`) directly, or
 * – access individual sections programmatically (e.g. for UI rendering, analytics, etc.).
 *
 * `metadata` can be used for generation timestamps, model version, or any other
 * bookkeeping the system wants to keep.
 */
export type MarketingResearchReport = {
    /**
     * Executive Summary
     *
     * High‑level overview of findings.
     */
    executive_summary: string;
    /**
     * Competitive Landscape
     *
     * Analysis of competitors identified.
     */
    competitive_landscape: string;
    /**
     * Emerging Trends
     *
     * Key trends tied to the campaign theme.
     */
    emerging_trends: string;
    /**
     * Successful Examples
     *
     * Relevant Instagram examples with usernames & URLs.
     */
    successful_examples: string;
    /**
     * Recommendations
     *
     * Actionable advice for the upcoming campaign.
     */
    recommendations: string;
    /**
     * References
     *
     * Citations of web‑search & Instagram sources.
     */
    references: string;
};

/**
 * OrshotDataType
 */
export type OrshotDataType = 'TEXT' | 'IMAGE' | 'BACKGROUND';

/**
 * OrshotSchemaField
 *
 * Represents a single configurable field in an Orshot Template.
 * User inputs a list of these objects to define the 'rules' for the template.
 */
export type OrshotSchemaField = {
    /**
     * Field
     *
     * The exact parameter key to modify in the Orshot template (e.g., 'headline', 'background_image')
     */
    field: string;
    /**
     * The data type of this field: 'TEXT' or 'IMAGE'
     */
    dataType: OrshotDataType;
    /**
     * Description
     *
     * Contextual description of the field (e.g., 'Main title, max 20 chars', 'Product shot in portrait mode')
     */
    description: string;
};

/**
 * RequiredInputField
 *
 * Represents a single required input field.
 */
export type RequiredInputField = {
    /**
     * Field Name
     *
     * Name of the field
     */
    field_name: string;
    /**
     * Type information for this field
     */
    type_info: FieldTypeInfo;
    /**
     * Field Kind
     *
     * Field kind: 'context' or 'data'
     */
    field_kind: string;
    /**
     * Required
     *
     * Whether this field is required (cannot be left blank)
     */
    required?: boolean;
    /**
     * Placeholder
     *
     * Placeholder text for the input field
     */
    placeholder?: string | null;
};

/**
 * RequiredInputsResponse
 *
 * Response model for required inputs endpoint.
 */
export type RequiredInputsResponse = {
    /**
     * Fields
     *
     * List of required input fields
     */
    fields: Array<RequiredInputField>;
};

/**
 * ScheduleItem
 *
 * Represents a single scheduled Instagram content unit (post, story, reel).
 * This is derived from the HTML table but stored in a structured way
 * for UI, analytics, or downstream processing.
 */
export type ScheduleItem = {
    /**
     * Phase Name
     *
     * Name of the strategy phase this item belongs to, if available.
     */
    phase_name?: string | null;
    /**
     * Week
     *
     * Week number within the campaign (1-based).
     */
    week: number;
    /**
     * Date
     *
     * Calendar date for this content.
     */
    date: string;
    /**
     * Post Type
     *
     * Type of content.
     */
    post_type: 'Post' | 'Story' | 'Reel';
    /**
     * Theme Concept
     *
     * Theme or concept for this content unit.
     */
    theme_concept: string;
    /**
     * Objective
     *
     * Objective for this content (e.g., awareness, engagement, CTA).
     */
    objective: string;
    /**
     * Description
     *
     * Detailed description to guide copy and visual creation.
     */
    description: string;
    /**
     * Notes
     *
     * Optional notes such as tags, CTA, stickers, collaborators, or audio suggestions.
     */
    notes?: string | null;
};

/**
 * SocialMediaSchedule
 *
 * Represents the final social media posting schedule.
 *
 * - `html_table`: The fully-formed HTML table that is compatible with the html_table_to_excel tool.
 * - `items`: Structured representation of each scheduled post/story/reel.
 */
export type SocialMediaSchedule = {
    /**
     * Items
     *
     * Flattened list of scheduled content items, one per row of the schedule (excluding header).
     */
    items: Array<ScheduleItem>;
};

/**
 * StrategyPhase
 *
 * Non-date-specific strategic phase definition.
 * The scheduler will later map these phases to calendar weeks.
 */
export type StrategyPhase = {
    /**
     * Name
     *
     * Phase name, e.g., 'Awareness', 'Engagement', etc.
     */
    name: string;
    /**
     * Duration In Weeks
     *
     * How long the phase should run, without calendar dates.
     */
    duration_in_weeks: number;
    /**
     * Themes
     *
     * Core themes emphasized in this phase.
     */
    themes: Array<string>;
    /**
     * Objectives
     *
     * Strategic objectives for the phase.
     */
    objectives: Array<string>;
    /**
     * Recommended Content Types
     *
     * Content formats recommended here (e.g., posts, reels, stories).
     */
    recommended_content_types: Array<string>;
    /**
     * Posting Cadence
     *
     * Cadence expressed as counts, e.g., {'posts_per_week': 3, 'stories_per_week': 2}
     */
    posting_cadence: {
        [key: string]: number;
    };
    /**
     * Messaging Guidelines
     *
     * Tone & message guidelines specific to this phase.
     */
    messaging_guidelines?: Array<string> | null;
};

/**
 * TaskInfo
 *
 * Task information exposed to the frontend.
 */
export type TaskInfo = {
    /**
     * Key
     */
    key: string;
    /**
     * Name
     */
    name: string;
    /**
     * Task Description
     */
    task_description: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type SystemCheckStatusHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status/health';
};

export type SystemCheckStatusHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRequiredInputsCrewCrewIdRequiredInputsGetData = {
    body?: never;
    path: {
        /**
         * Crew Id
         */
        crew_id: string;
    };
    query?: never;
    url: '/crew/{crew_id}/required-inputs';
};

export type GetRequiredInputsCrewCrewIdRequiredInputsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRequiredInputsCrewCrewIdRequiredInputsGetError = GetRequiredInputsCrewCrewIdRequiredInputsGetErrors[keyof GetRequiredInputsCrewCrewIdRequiredInputsGetErrors];

export type GetRequiredInputsCrewCrewIdRequiredInputsGetResponses = {
    /**
     * Successful Response
     */
    200: RequiredInputsResponse;
};

export type GetRequiredInputsCrewCrewIdRequiredInputsGetResponse = GetRequiredInputsCrewCrewIdRequiredInputsGetResponses[keyof GetRequiredInputsCrewCrewIdRequiredInputsGetResponses];

export type CrewKickoffCrewKickoffPostData = {
    body: CrewRunCreateRequest;
    path?: never;
    query?: never;
    url: '/crew/kickoff';
};

export type CrewKickoffCrewKickoffPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CrewKickoffCrewKickoffPostError = CrewKickoffCrewKickoffPostErrors[keyof CrewKickoffCrewKickoffPostErrors];

export type CrewKickoffCrewKickoffPostResponses = {
    /**
     * Successful Response
     */
    201: CrewRun;
};

export type CrewKickoffCrewKickoffPostResponse = CrewKickoffCrewKickoffPostResponses[keyof CrewKickoffCrewKickoffPostResponses];

export type GetPreDefinedTasksTasksPreDefinedGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tasks/pre-defined';
};

export type GetPreDefinedTasksTasksPreDefinedGetResponses = {
    /**
     * Response Get Pre Defined Tasks Tasks Pre Defined Get
     *
     * Successful Response
     */
    200: Array<TaskInfo>;
};

export type GetPreDefinedTasksTasksPreDefinedGetResponse = GetPreDefinedTasksTasksPreDefinedGetResponses[keyof GetPreDefinedTasksTasksPreDefinedGetResponses];

export type GetCustomTypeSchemasSchemasGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/schemas/';
};

export type GetCustomTypeSchemasSchemasGetResponses = {
    /**
     * Successful Response
     */
    200: CustomTypesResponse;
};

export type GetCustomTypeSchemasSchemasGetResponse = GetCustomTypeSchemasSchemasGetResponses[keyof GetCustomTypeSchemasSchemasGetResponses];
