// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateCrewCrewPostData, CreateCrewCrewPostErrors, CreateCrewCrewPostResponses, CreateTaskTaskCrewIdPostData, CreateTaskTaskCrewIdPostErrors, CreateTaskTaskCrewIdPostResponses, GetCrewsCrewGetData, GetCrewsCrewGetErrors, GetCrewsCrewGetResponses, GetUserByIdUserGetData, GetUserByIdUserGetResponses, ReplaceAllTasksForCrewTaskCrewIdSavePutData, ReplaceAllTasksForCrewTaskCrewIdSavePutErrors, ReplaceAllTasksForCrewTaskCrewIdSavePutResponses, SyncUserUserSyncPostData, SyncUserUserSyncPostResponses, SystemCheckStatusHealthGetData, SystemCheckStatusHealthGetResponses, UpdateCrewCrewPutData, UpdateCrewCrewPutErrors, UpdateCrewCrewPutResponses, UpdateOneTaskTaskCrewIdPatchData, UpdateOneTaskTaskCrewIdPatchErrors, UpdateOneTaskTaskCrewIdPatchResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * System Check
 */
export const systemCheckStatusHealthGet = <ThrowOnError extends boolean = false>(options?: Options<SystemCheckStatusHealthGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<SystemCheckStatusHealthGetResponses, unknown, ThrowOnError>({
        url: '/status/health',
        ...options
    });
};

/**
 * Get Crews
 *
 * Get crews, optionally filtered by crew_id.
 */
export const getCrewsCrewGet = <ThrowOnError extends boolean = false>(options?: Options<GetCrewsCrewGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetCrewsCrewGetResponses, GetCrewsCrewGetErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/crew/',
        ...options
    });
};

/**
 * Create Crew
 *
 * Create a new crew.
 */
export const createCrewCrewPost = <ThrowOnError extends boolean = false>(options: Options<CreateCrewCrewPostData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateCrewCrewPostResponses, CreateCrewCrewPostErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/crew/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Update Crew
 *
 * Update an existing crew.
 */
export const updateCrewCrewPut = <ThrowOnError extends boolean = false>(options: Options<UpdateCrewCrewPutData, ThrowOnError>) => {
    return (options.client ?? client).put<UpdateCrewCrewPutResponses, UpdateCrewCrewPutErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/crew/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Update One Task
 *
 * Update one task.
 */
export const updateOneTaskTaskCrewIdPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateOneTaskTaskCrewIdPatchData, ThrowOnError>) => {
    return (options.client ?? client).patch<UpdateOneTaskTaskCrewIdPatchResponses, UpdateOneTaskTaskCrewIdPatchErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/task/{crew_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Create Task
 *
 * Create a new task.
 */
export const createTaskTaskCrewIdPost = <ThrowOnError extends boolean = false>(options: Options<CreateTaskTaskCrewIdPostData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateTaskTaskCrewIdPostResponses, CreateTaskTaskCrewIdPostErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/task/{crew_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Replace All Tasks For Crew
 *
 * Replace all tasks for a crew.
 */
export const replaceAllTasksForCrewTaskCrewIdSavePut = <ThrowOnError extends boolean = false>(options: Options<ReplaceAllTasksForCrewTaskCrewIdSavePutData, ThrowOnError>) => {
    return (options.client ?? client).put<ReplaceAllTasksForCrewTaskCrewIdSavePutResponses, ReplaceAllTasksForCrewTaskCrewIdSavePutErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/task/{crew_id}/save',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Sync User
 *
 * Sync/create user in database from JWT token.
 */
export const syncUserUserSyncPost = <ThrowOnError extends boolean = false>(options?: Options<SyncUserUserSyncPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<SyncUserUserSyncPostResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/user/sync',
        ...options
    });
};

/**
 * Get User By Id
 *
 * Get user by ID. Users can only access their own profile.
 */
export const getUserByIdUserGet = <ThrowOnError extends boolean = false>(options?: Options<GetUserByIdUserGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUserByIdUserGetResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/user/',
        ...options
    });
};
