// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * ArtifactRead
 */
export type ArtifactRead = {
    type: ArtifactType;
    /**
     * File Name
     */
    file_name: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Crew Run Id
     */
    crew_run_id: string;
};

/**
 * ArtifactServerCreate
 */
export type ArtifactServerCreate = {
    type: ArtifactType;
    /**
     * File Name
     */
    file_name: string | null;
    /**
     * File Content Base64
     */
    file_content_base64: string;
};

/**
 * ArtifactType
 */
export type ArtifactType = 'TEXT' | 'IMAGE' | 'VIDEO' | 'AUDIO' | 'DOCUMENT' | 'OTHER';

/**
 * Body_create_crew_run_internal_internal_crew_run_create_post
 */
export type BodyCreateCrewRunInternalInternalCrewRunCreatePost = {
    /**
     * Crew run data to create
     */
    crew_run_data: CrewRunCreate;
    /**
     * User Token
     *
     * User's JWT token for authentication
     */
    user_token: string;
};

/**
 * ClaimJobResponse
 */
export type ClaimJobResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Crew Run Id
     */
    crew_run_id: string;
    /**
     * Crew Id
     */
    crew_id: string;
    status: QueueStatus;
    /**
     * Lease Token
     */
    lease_token: string;
    /**
     * Visible At
     */
    visible_at: string;
};

/**
 * CrewCreate
 */
export type CrewCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * CrewRead
 */
export type CrewRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Tasks
     */
    tasks: Array<TaskRead>;
    /**
     * Crew Runs
     */
    crew_runs?: Array<CrewRunRead> | null;
};

/**
 * CrewRunCreate
 */
export type CrewRunCreate = {
    /**
     * Output
     */
    output?: {
        [key: string]: unknown;
    } | null;
    run_metadata?: CrewRunMetadata | null;
    /**
     * Crew Id
     */
    crew_id: string;
};

/**
 * CrewRunMetadata
 */
export type CrewRunMetadata = {
    /**
     * Inputs
     */
    inputs: {
        [key: string]: unknown;
    };
    /**
     * Task Nodes
     */
    task_nodes?: Array<{
        [key: string]: unknown;
    }> | null;
};

/**
 * CrewRunRead
 */
export type CrewRunRead = {
    /**
     * Output
     */
    output?: {
        [key: string]: unknown;
    } | null;
    run_metadata?: CrewRunMetadata | null;
    /**
     * Id
     */
    id: string;
    /**
     * Crew Id
     */
    crew_id: string;
    /**
     * Artifacts
     */
    artifacts?: Array<ArtifactRead> | null;
    queue_status?: QueueStatus | null;
    /**
     * Retry Count
     */
    retry_count?: number | null;
};

/**
 * CrewUpdate
 */
export type CrewUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Id
     */
    id: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HeartbeatRequest
 */
export type HeartbeatRequest = {
    /**
     * Lease Token
     */
    lease_token: string;
};

/**
 * QueueStatus
 */
export type QueueStatus = 'QUEUED' | 'CLAIMED' | 'COMPLETED' | 'FAILED';

/**
 * TaskCreate
 */
export type TaskCreate = {
    /**
     * Key
     */
    key: string;
    /**
     * Order
     */
    order: number;
};

/**
 * TaskRead
 */
export type TaskRead = {
    /**
     * Key
     */
    key: string;
    /**
     * Order
     */
    order: number;
    /**
     * Id
     */
    id: string;
};

/**
 * TaskUpdate
 */
export type TaskUpdate = {
    /**
     * Key
     */
    key: string;
    /**
     * Order
     */
    order: number;
    /**
     * Id
     */
    id: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Expected Output
     */
    expected_output?: string | null;
};

/**
 * UpdateStatusRequest
 */
export type UpdateStatusRequest = {
    /**
     * Lease Token
     */
    lease_token: string;
    status: QueueStatus;
};

/**
 * User
 */
export type User = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
    /**
     * Given Name
     */
    given_name: string;
    /**
     * Family Name
     */
    family_name: string;
    /**
     * Picture
     */
    picture: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type SystemCheckStatusHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status/health';
};

export type SystemCheckStatusHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteCrewCrewCrewIdDeleteData = {
    body?: never;
    path: {
        /**
         * Crew Id
         */
        crew_id: string;
    };
    query?: never;
    url: '/crew/{crew_id}';
};

export type DeleteCrewCrewCrewIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCrewCrewCrewIdDeleteError = DeleteCrewCrewCrewIdDeleteErrors[keyof DeleteCrewCrewCrewIdDeleteErrors];

export type DeleteCrewCrewCrewIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCrewCrewCrewIdDeleteResponse = DeleteCrewCrewCrewIdDeleteResponses[keyof DeleteCrewCrewCrewIdDeleteResponses];

export type GetCrewByIdCrewCrewIdGetData = {
    body?: never;
    path: {
        /**
         * Crew Id
         *
         * Crew ID to retrieve
         */
        crew_id: string;
    };
    query?: never;
    url: '/crew/{crew_id}';
};

export type GetCrewByIdCrewCrewIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCrewByIdCrewCrewIdGetError = GetCrewByIdCrewCrewIdGetErrors[keyof GetCrewByIdCrewCrewIdGetErrors];

export type GetCrewByIdCrewCrewIdGetResponses = {
    /**
     * Successful Response
     */
    200: CrewRead;
};

export type GetCrewByIdCrewCrewIdGetResponse = GetCrewByIdCrewCrewIdGetResponses[keyof GetCrewByIdCrewCrewIdGetResponses];

export type GetAllCrewsCrewGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/crew/';
};

export type GetAllCrewsCrewGetResponses = {
    /**
     * Response Get All Crews Crew  Get
     *
     * Successful Response
     */
    200: Array<CrewRead>;
};

export type GetAllCrewsCrewGetResponse = GetAllCrewsCrewGetResponses[keyof GetAllCrewsCrewGetResponses];

export type CreateCrewCrewPostData = {
    body: CrewCreate;
    path?: never;
    query?: never;
    url: '/crew/';
};

export type CreateCrewCrewPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCrewCrewPostError = CreateCrewCrewPostErrors[keyof CreateCrewCrewPostErrors];

export type CreateCrewCrewPostResponses = {
    /**
     * Successful Response
     */
    201: CrewRead;
};

export type CreateCrewCrewPostResponse = CreateCrewCrewPostResponses[keyof CreateCrewCrewPostResponses];

export type UpdateCrewCrewPutData = {
    body: CrewUpdate;
    path?: never;
    query?: never;
    url: '/crew/';
};

export type UpdateCrewCrewPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCrewCrewPutError = UpdateCrewCrewPutErrors[keyof UpdateCrewCrewPutErrors];

export type UpdateCrewCrewPutResponses = {
    /**
     * Successful Response
     */
    200: CrewRead;
};

export type UpdateCrewCrewPutResponse = UpdateCrewCrewPutResponses[keyof UpdateCrewCrewPutResponses];

export type UpdateOneTaskTaskCrewIdPatchData = {
    body: TaskUpdate;
    path: {
        /**
         * Crew Id
         *
         * Crew ID to associate the task with
         */
        crew_id: string;
    };
    query?: never;
    url: '/task/{crew_id}';
};

export type UpdateOneTaskTaskCrewIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateOneTaskTaskCrewIdPatchError = UpdateOneTaskTaskCrewIdPatchErrors[keyof UpdateOneTaskTaskCrewIdPatchErrors];

export type UpdateOneTaskTaskCrewIdPatchResponses = {
    /**
     * Response Update One Task Task  Crew Id  Patch
     *
     * Successful Response
     */
    200: Array<TaskRead>;
};

export type UpdateOneTaskTaskCrewIdPatchResponse = UpdateOneTaskTaskCrewIdPatchResponses[keyof UpdateOneTaskTaskCrewIdPatchResponses];

export type CreateTaskTaskCrewIdPostData = {
    body: TaskCreate;
    path: {
        /**
         * Crew Id
         *
         * Crew ID to associate the task with
         */
        crew_id: string;
    };
    query?: never;
    url: '/task/{crew_id}';
};

export type CreateTaskTaskCrewIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTaskTaskCrewIdPostError = CreateTaskTaskCrewIdPostErrors[keyof CreateTaskTaskCrewIdPostErrors];

export type CreateTaskTaskCrewIdPostResponses = {
    /**
     * Successful Response
     */
    201: TaskRead;
};

export type CreateTaskTaskCrewIdPostResponse = CreateTaskTaskCrewIdPostResponses[keyof CreateTaskTaskCrewIdPostResponses];

export type ReplaceAllTasksForCrewTaskCrewIdSavePutData = {
    /**
     * Tasks
     */
    body: Array<TaskCreate>;
    path: {
        /**
         * Crew Id
         *
         * Crew ID to associate the task with
         */
        crew_id: string;
    };
    query?: never;
    url: '/task/{crew_id}/save';
};

export type ReplaceAllTasksForCrewTaskCrewIdSavePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReplaceAllTasksForCrewTaskCrewIdSavePutError = ReplaceAllTasksForCrewTaskCrewIdSavePutErrors[keyof ReplaceAllTasksForCrewTaskCrewIdSavePutErrors];

export type ReplaceAllTasksForCrewTaskCrewIdSavePutResponses = {
    /**
     * Response Replace All Tasks For Crew Task  Crew Id  Save Put
     *
     * Successful Response
     */
    200: Array<TaskRead>;
};

export type ReplaceAllTasksForCrewTaskCrewIdSavePutResponse = ReplaceAllTasksForCrewTaskCrewIdSavePutResponses[keyof ReplaceAllTasksForCrewTaskCrewIdSavePutResponses];

export type SyncUserUserSyncPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/sync';
};

export type SyncUserUserSyncPostResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type SyncUserUserSyncPostResponse = SyncUserUserSyncPostResponses[keyof SyncUserUserSyncPostResponses];

export type GetUserByIdUserGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/';
};

export type GetUserByIdUserGetResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type GetUserByIdUserGetResponse = GetUserByIdUserGetResponses[keyof GetUserByIdUserGetResponses];

export type CreateArtifactArtifactCrewRunIdPostData = {
    body: ArtifactServerCreate;
    path: {
        /**
         * Crew Run Id
         *
         * Crew Run ID to associate the artifact with
         */
        crew_run_id: string;
    };
    query?: never;
    url: '/artifact/{crew_run_id}';
};

export type CreateArtifactArtifactCrewRunIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateArtifactArtifactCrewRunIdPostError = CreateArtifactArtifactCrewRunIdPostErrors[keyof CreateArtifactArtifactCrewRunIdPostErrors];

export type CreateArtifactArtifactCrewRunIdPostResponses = {
    /**
     * Successful Response
     */
    201: ArtifactRead;
};

export type CreateArtifactArtifactCrewRunIdPostResponse = CreateArtifactArtifactCrewRunIdPostResponses[keyof CreateArtifactArtifactCrewRunIdPostResponses];

export type GetArtifactArtifactArtifactIdGetData = {
    body?: never;
    path: {
        /**
         * Artifact Id
         *
         * Artifact ID to retrieve
         */
        artifact_id: string;
    };
    query?: never;
    url: '/artifact/{artifact_id}';
};

export type GetArtifactArtifactArtifactIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetArtifactArtifactArtifactIdGetError = GetArtifactArtifactArtifactIdGetErrors[keyof GetArtifactArtifactArtifactIdGetErrors];

export type GetArtifactArtifactArtifactIdGetResponses = {
    /**
     * Response Get Artifact Artifact  Artifact Id  Get
     *
     * Successful Response
     */
    200: string;
};

export type GetArtifactArtifactArtifactIdGetResponse = GetArtifactArtifactArtifactIdGetResponses[keyof GetArtifactArtifactArtifactIdGetResponses];

export type GetCrewRunCrewRunCrewRunIdGetData = {
    body?: never;
    path: {
        /**
         * Crew Run Id
         *
         * Crew Run ID to retrieve
         */
        crew_run_id: string;
    };
    query?: never;
    url: '/crew-run/{crew_run_id}';
};

export type GetCrewRunCrewRunCrewRunIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCrewRunCrewRunCrewRunIdGetError = GetCrewRunCrewRunCrewRunIdGetErrors[keyof GetCrewRunCrewRunCrewRunIdGetErrors];

export type GetCrewRunCrewRunCrewRunIdGetResponses = {
    /**
     * Successful Response
     */
    200: CrewRunRead;
};

export type GetCrewRunCrewRunCrewRunIdGetResponse = GetCrewRunCrewRunCrewRunIdGetResponses[keyof GetCrewRunCrewRunCrewRunIdGetResponses];

export type GetCrewByIdInternalCrewCrewIdGetData = {
    body?: never;
    headers?: {
        /**
         * X-Internal-Api-Key
         */
        'X-Internal-Api-Key'?: string | null;
    };
    path: {
        /**
         * Crew Id
         *
         * Crew ID to retrieve
         */
        crew_id: string;
    };
    query?: never;
    url: '/internal/crew/{crew_id}';
};

export type GetCrewByIdInternalCrewCrewIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCrewByIdInternalCrewCrewIdGetError = GetCrewByIdInternalCrewCrewIdGetErrors[keyof GetCrewByIdInternalCrewCrewIdGetErrors];

export type GetCrewByIdInternalCrewCrewIdGetResponses = {
    /**
     * Successful Response
     */
    200: CrewRead;
};

export type GetCrewByIdInternalCrewCrewIdGetResponse = GetCrewByIdInternalCrewCrewIdGetResponses[keyof GetCrewByIdInternalCrewCrewIdGetResponses];

export type GetCrewRunByIdInternalCrewRunCrewRunIdGetData = {
    body?: never;
    headers?: {
        /**
         * X-Internal-Api-Key
         */
        'X-Internal-Api-Key'?: string | null;
    };
    path: {
        /**
         * Crew Run Id
         *
         * Crew Run ID to retrieve
         */
        crew_run_id: string;
    };
    query?: never;
    url: '/internal/crew-run/{crew_run_id}';
};

export type GetCrewRunByIdInternalCrewRunCrewRunIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCrewRunByIdInternalCrewRunCrewRunIdGetError = GetCrewRunByIdInternalCrewRunCrewRunIdGetErrors[keyof GetCrewRunByIdInternalCrewRunCrewRunIdGetErrors];

export type GetCrewRunByIdInternalCrewRunCrewRunIdGetResponses = {
    /**
     * Successful Response
     */
    200: CrewRunRead;
};

export type GetCrewRunByIdInternalCrewRunCrewRunIdGetResponse = GetCrewRunByIdInternalCrewRunCrewRunIdGetResponses[keyof GetCrewRunByIdInternalCrewRunCrewRunIdGetResponses];

export type CreateCrewRunInternalInternalCrewRunCreatePostData = {
    body: BodyCreateCrewRunInternalInternalCrewRunCreatePost;
    headers?: {
        /**
         * X-Internal-Api-Key
         */
        'X-Internal-Api-Key'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/internal/crew-run/create';
};

export type CreateCrewRunInternalInternalCrewRunCreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCrewRunInternalInternalCrewRunCreatePostError = CreateCrewRunInternalInternalCrewRunCreatePostErrors[keyof CreateCrewRunInternalInternalCrewRunCreatePostErrors];

export type CreateCrewRunInternalInternalCrewRunCreatePostResponses = {
    /**
     * Successful Response
     */
    201: CrewRunRead;
};

export type CreateCrewRunInternalInternalCrewRunCreatePostResponse = CreateCrewRunInternalInternalCrewRunCreatePostResponses[keyof CreateCrewRunInternalInternalCrewRunCreatePostResponses];

export type UpdateCrewRunOutputInternalInternalCrewRunCrewRunIdOutputPutData = {
    /**
     * Output
     *
     * Output data to update
     */
    body: {
        [key: string]: unknown;
    };
    headers?: {
        /**
         * X-Internal-Api-Key
         */
        'X-Internal-Api-Key'?: string | null;
    };
    path: {
        /**
         * Crew Run Id
         *
         * Crew Run ID to update
         */
        crew_run_id: string;
    };
    query?: never;
    url: '/internal/crew-run/{crew_run_id}/output';
};

export type UpdateCrewRunOutputInternalInternalCrewRunCrewRunIdOutputPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCrewRunOutputInternalInternalCrewRunCrewRunIdOutputPutError = UpdateCrewRunOutputInternalInternalCrewRunCrewRunIdOutputPutErrors[keyof UpdateCrewRunOutputInternalInternalCrewRunCrewRunIdOutputPutErrors];

export type UpdateCrewRunOutputInternalInternalCrewRunCrewRunIdOutputPutResponses = {
    /**
     * Successful Response
     */
    200: CrewRunRead;
};

export type UpdateCrewRunOutputInternalInternalCrewRunCrewRunIdOutputPutResponse = UpdateCrewRunOutputInternalInternalCrewRunCrewRunIdOutputPutResponses[keyof UpdateCrewRunOutputInternalInternalCrewRunCrewRunIdOutputPutResponses];

export type ClaimNextJobInternalInternalQueueClaimPostData = {
    body?: never;
    headers?: {
        /**
         * X-Internal-Api-Key
         */
        'X-Internal-Api-Key'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Visibility Timeout Seconds
         */
        visibility_timeout_seconds?: number;
    };
    url: '/internal/queue/claim';
};

export type ClaimNextJobInternalInternalQueueClaimPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ClaimNextJobInternalInternalQueueClaimPostError = ClaimNextJobInternalInternalQueueClaimPostErrors[keyof ClaimNextJobInternalInternalQueueClaimPostErrors];

export type ClaimNextJobInternalInternalQueueClaimPostResponses = {
    /**
     * Response Claim Next Job Internal Internal Queue Claim Post
     *
     * Successful Response
     */
    200: ClaimJobResponse | null;
};

export type ClaimNextJobInternalInternalQueueClaimPostResponse = ClaimNextJobInternalInternalQueueClaimPostResponses[keyof ClaimNextJobInternalInternalQueueClaimPostResponses];

export type UpdateQueueStatusInternalInternalQueueQueueIdStatusPutData = {
    body: UpdateStatusRequest;
    headers?: {
        /**
         * X-Internal-Api-Key
         */
        'X-Internal-Api-Key'?: string | null;
    };
    path: {
        /**
         * Queue Id
         */
        queue_id: string;
    };
    query?: never;
    url: '/internal/queue/{queue_id}/status';
};

export type UpdateQueueStatusInternalInternalQueueQueueIdStatusPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateQueueStatusInternalInternalQueueQueueIdStatusPutError = UpdateQueueStatusInternalInternalQueueQueueIdStatusPutErrors[keyof UpdateQueueStatusInternalInternalQueueQueueIdStatusPutErrors];

export type UpdateQueueStatusInternalInternalQueueQueueIdStatusPutResponses = {
    /**
     * Response Update Queue Status Internal Internal Queue  Queue Id  Status Put
     *
     * Successful Response
     */
    200: ClaimJobResponse | null;
};

export type UpdateQueueStatusInternalInternalQueueQueueIdStatusPutResponse = UpdateQueueStatusInternalInternalQueueQueueIdStatusPutResponses[keyof UpdateQueueStatusInternalInternalQueueQueueIdStatusPutResponses];

export type HeartbeatInternalInternalQueueQueueIdHeartbeatPostData = {
    body: HeartbeatRequest;
    headers?: {
        /**
         * X-Internal-Api-Key
         */
        'X-Internal-Api-Key'?: string | null;
    };
    path: {
        /**
         * Queue Id
         */
        queue_id: string;
    };
    query?: {
        /**
         * Visibility Timeout Seconds
         */
        visibility_timeout_seconds?: number;
    };
    url: '/internal/queue/{queue_id}/heartbeat';
};

export type HeartbeatInternalInternalQueueQueueIdHeartbeatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HeartbeatInternalInternalQueueQueueIdHeartbeatPostError = HeartbeatInternalInternalQueueQueueIdHeartbeatPostErrors[keyof HeartbeatInternalInternalQueueQueueIdHeartbeatPostErrors];

export type HeartbeatInternalInternalQueueQueueIdHeartbeatPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
