// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Agent
 */
export type Agent = {
    /**
     * Key
     */
    key: string;
    /**
     * Role
     */
    role: string;
    /**
     * Goal
     */
    goal: string;
    /**
     * Backstory
     */
    backstory: string;
};

/**
 * CrewBase
 */
export type CrewBase = {
    /**
     * Name
     */
    name: string;
};

/**
 * CrewRead
 */
export type CrewRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Tasks
     */
    tasks: Array<TaskRead>;
    /**
     * Agents
     */
    agents: Array<Agent>;
};

/**
 * CrewUpdate
 */
export type CrewUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Id
     */
    id: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * TaskCreate
 */
export type TaskCreate = {
    /**
     * Key
     */
    key: string;
    /**
     * Description
     */
    description: string;
    /**
     * Expected Output
     */
    expected_output: string;
    /**
     * Order
     */
    order: number;
    /**
     * Agent Key
     */
    agent_key?: string | null;
};

/**
 * TaskRead
 */
export type TaskRead = {
    /**
     * Key
     */
    key: string;
    /**
     * Description
     */
    description: string;
    /**
     * Expected Output
     */
    expected_output: string;
    /**
     * Order
     */
    order: number;
    /**
     * Id
     */
    id: string;
    /**
     * Agent Key
     */
    agent_key: string;
};

/**
 * TaskUpdate
 */
export type TaskUpdate = {
    /**
     * Key
     */
    key: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Expected Output
     */
    expected_output?: string | null;
    /**
     * Order
     */
    order: number;
    /**
     * Id
     */
    id: string;
};

/**
 * User
 */
export type User = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
    /**
     * Given Name
     */
    given_name: string;
    /**
     * Family Name
     */
    family_name: string;
    /**
     * Picture
     */
    picture: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type SystemCheckStatusHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status/health';
};

export type SystemCheckStatusHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCrewsCrewGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Crew Id
         *
         * Optional Crew ID to filter
         */
        crew_id?: string | null;
    };
    url: '/crew/';
};

export type GetCrewsCrewGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCrewsCrewGetError = GetCrewsCrewGetErrors[keyof GetCrewsCrewGetErrors];

export type GetCrewsCrewGetResponses = {
    /**
     * Response Get Crews Crew  Get
     *
     * Successful Response
     */
    200: CrewRead | Array<CrewRead>;
};

export type GetCrewsCrewGetResponse = GetCrewsCrewGetResponses[keyof GetCrewsCrewGetResponses];

export type CreateCrewCrewPostData = {
    body: CrewBase;
    path?: never;
    query?: never;
    url: '/crew/';
};

export type CreateCrewCrewPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCrewCrewPostError = CreateCrewCrewPostErrors[keyof CreateCrewCrewPostErrors];

export type CreateCrewCrewPostResponses = {
    /**
     * Successful Response
     */
    201: CrewRead;
};

export type CreateCrewCrewPostResponse = CreateCrewCrewPostResponses[keyof CreateCrewCrewPostResponses];

export type UpdateCrewCrewPutData = {
    body: CrewUpdate;
    path?: never;
    query?: never;
    url: '/crew/';
};

export type UpdateCrewCrewPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCrewCrewPutError = UpdateCrewCrewPutErrors[keyof UpdateCrewCrewPutErrors];

export type UpdateCrewCrewPutResponses = {
    /**
     * Successful Response
     */
    200: CrewRead;
};

export type UpdateCrewCrewPutResponse = UpdateCrewCrewPutResponses[keyof UpdateCrewCrewPutResponses];

export type UpdateOneTaskTaskCrewIdPatchData = {
    body: TaskUpdate;
    path: {
        /**
         * Crew Id
         *
         * Crew ID to associate the task with
         */
        crew_id: string;
    };
    query?: never;
    url: '/task/{crew_id}';
};

export type UpdateOneTaskTaskCrewIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateOneTaskTaskCrewIdPatchError = UpdateOneTaskTaskCrewIdPatchErrors[keyof UpdateOneTaskTaskCrewIdPatchErrors];

export type UpdateOneTaskTaskCrewIdPatchResponses = {
    /**
     * Response Update One Task Task  Crew Id  Patch
     *
     * Successful Response
     */
    200: Array<TaskRead>;
};

export type UpdateOneTaskTaskCrewIdPatchResponse = UpdateOneTaskTaskCrewIdPatchResponses[keyof UpdateOneTaskTaskCrewIdPatchResponses];

export type CreateTaskTaskCrewIdPostData = {
    body: TaskCreate;
    path: {
        /**
         * Crew Id
         *
         * Crew ID to associate the task with
         */
        crew_id: string;
    };
    query?: never;
    url: '/task/{crew_id}';
};

export type CreateTaskTaskCrewIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTaskTaskCrewIdPostError = CreateTaskTaskCrewIdPostErrors[keyof CreateTaskTaskCrewIdPostErrors];

export type CreateTaskTaskCrewIdPostResponses = {
    /**
     * Successful Response
     */
    201: TaskRead;
};

export type CreateTaskTaskCrewIdPostResponse = CreateTaskTaskCrewIdPostResponses[keyof CreateTaskTaskCrewIdPostResponses];

export type ReplaceAllTasksForCrewTaskCrewIdSavePutData = {
    /**
     * Tasks
     */
    body: Array<TaskCreate>;
    path: {
        /**
         * Crew Id
         *
         * Crew ID to associate the task with
         */
        crew_id: string;
    };
    query?: never;
    url: '/task/{crew_id}/save';
};

export type ReplaceAllTasksForCrewTaskCrewIdSavePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReplaceAllTasksForCrewTaskCrewIdSavePutError = ReplaceAllTasksForCrewTaskCrewIdSavePutErrors[keyof ReplaceAllTasksForCrewTaskCrewIdSavePutErrors];

export type ReplaceAllTasksForCrewTaskCrewIdSavePutResponses = {
    /**
     * Response Replace All Tasks For Crew Task  Crew Id  Save Put
     *
     * Successful Response
     */
    200: Array<TaskRead>;
};

export type ReplaceAllTasksForCrewTaskCrewIdSavePutResponse = ReplaceAllTasksForCrewTaskCrewIdSavePutResponses[keyof ReplaceAllTasksForCrewTaskCrewIdSavePutResponses];

export type SyncUserUserSyncPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/sync';
};

export type SyncUserUserSyncPostResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type SyncUserUserSyncPostResponse = SyncUserUserSyncPostResponses[keyof SyncUserUserSyncPostResponses];

export type GetUserByIdUserGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/';
};

export type GetUserByIdUserGetResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type GetUserByIdUserGetResponse = GetUserByIdUserGetResponses[keyof GetUserByIdUserGetResponses];
