"""create_crew_run_queue_table

Revision ID: 12be34280469
Revises: update_uuid_defaults
Create Date: 2025-11-19 16:32:33.043911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12be34280469'
down_revision: Union[str, Sequence[str], None] = 'update_uuid_defaults'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.create_table('crew_run_queue',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('crew_run_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'CLAIMED', 'COMPLETED', 'FAILED', name='queuestatus'), nullable=False),
    sa.Column('visible_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('lease_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['crew_run_id'], ['crew_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crew_run_id')
    )
    
    op.create_index('idx_queue_status_visible_created', 'crew_run_queue', ['status', 'visible_at', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_queue_status_visible_created', table_name='crew_run_queue')
    op.drop_table('crew_run_queue')
    op.execute("DROP TYPE IF EXISTS queuestatus") 
    # ### end Alembic commands ###
