"""add_cascading_deletes

Revision ID: 4bae9fc6985f
Revises: 752710caad09
Create Date: 2025-11-25 23:25:42.070815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bae9fc6985f'
down_revision: Union[str, Sequence[str], None] = '752710caad09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('artifacts_crew_run_id_fkey'), 'artifacts', type_='foreignkey')
    op.create_foreign_key(None, 'artifacts', 'crew_runs', ['crew_run_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('crew_run_queue_crew_run_id_fkey'), 'crew_run_queue', type_='foreignkey')
    op.create_foreign_key(None, 'crew_run_queue', 'crew_runs', ['crew_run_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('crew_runs_crew_id_fkey'), 'crew_runs', type_='foreignkey')
    op.create_foreign_key(None, 'crew_runs', 'crews', ['crew_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('crews_user_id_fkey'), 'crews', type_='foreignkey')
    op.create_foreign_key(None, 'crews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tasks_crew_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'crews', ['crew_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # 1. artifacts table:
    op.drop_constraint("artifacts_crew_run_id_fkey", 'artifacts', type_='foreignkey')
    op.create_foreign_key(op.f('artifacts_crew_run_id_fkey'), 'artifacts', 'crew_runs', ['crew_run_id'], ['id'])
    
    # 2. crew_run_queue table:
    op.drop_constraint("crew_run_queue_crew_run_id_fkey", 'crew_run_queue', type_='foreignkey')
    op.create_foreign_key(op.f('crew_run_queue_crew_run_id_fkey'), 'crew_run_queue', 'crew_runs', ['crew_run_id'], ['id'])

    # 3. crew_runs table:
    op.drop_constraint("crew_runs_crew_id_fkey", 'crew_runs', type_='foreignkey')
    op.create_foreign_key(op.f('crew_runs_crew_id_fkey'), 'crew_runs', 'crews', ['crew_id'], ['id'])
    
    # 4. crews table:
    op.drop_constraint("crews_user_id_fkey", 'crews', type_='foreignkey')
    op.create_foreign_key(op.f('crews_user_id_fkey'), 'crews', 'users', ['user_id'], ['id'])

    # 5. tasks table:
    op.drop_constraint("tasks_crew_id_fkey", 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_crew_id_fkey'), 'tasks', 'crews', ['crew_id'], ['id'])
    # ### end Alembic commands ###
