"""add_retry_count_col

Revision ID: 752710caad09
Revises: 12be34280469
Create Date: 2025-11-22 13:09:16.104443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '752710caad09'
down_revision: Union[str, Sequence[str], None] = '12be34280469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crew_run_queue', sa.Column('retry_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crew_run_queue', 'retry_count')
    # ### end Alembic commands ###
