"""add

Revision ID: bd0cf7cd05b0
Revises: eef34771c336
Create Date: 2025-12-03 05:06:36.767516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd0cf7cd05b0'
down_revision: Union[str, Sequence[str], None] = 'eef34771c336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crew_run_queue', sa.Column('cancel_requested', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crew_run_queue', 'cancel_requested')
    # ### end Alembic commands ###
