"""remove_agent_key_col

Revision ID: cd1452694ffa
Revises: 260dcf0fff0e
Create Date: 2025-11-26 21:55:15.009593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1452694ffa'
down_revision: Union[str, Sequence[str], None] = '260dcf0fff0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'agent_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('agent_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
