"""initialize_db

Revision ID: d81444e5227e
Revises: 
Create Date: 2025-11-08 04:19:19.075345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd81444e5227e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('given_name', sa.String(), nullable=False),
    sa.Column('family_name', sa.String(), nullable=False),
    sa.Column('picture', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crew_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('crew_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('agent_key', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('crew_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'IMAGE', 'VIDEO', 'AUDIO', 'DOCUMENT', 'OTHER', name='artifacttype'), nullable=False),
    sa.Column('object_key', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('crew_run_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['crew_run_id'], ['crew_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artifacts')
    op.drop_table('tasks')
    op.drop_table('crew_runs')
    op.drop_table('crews')
    op.drop_table('users')
    op.execute("DROP TYPE IF EXISTS artifacttype")
    # ### end Alembic commands ###