import os
import base64
from typing import Type
from uuid import UUID
from google import genai
from google.genai import types

from crewai.tools import BaseTool
from pydantic import BaseModel, Field

from app.api.crud_client import AuthenticatedClient
from app.api.crud_client.api.artifact import (
    create_artifact_artifact_crew_run_id_post, 
    get_artifact_artifact_artifact_id_get
)
from app.api.crud_client.models.artifact_server_create import ArtifactServerCreate
from app.api.crud_client.models.artifact_type import ArtifactType
from app.api.crud_client.models.artifact_read import ArtifactRead
from config import settings

class GenerateImagenInput(BaseModel):
    prompt: str = Field(..., description="A detailed description of the image to generate.")
    crew_run_id: str = Field(..., description="The UUID of the current crew run.")

class GenerateImagenTool(BaseTool):
    name: str = "generate_imagen_tool"
    description: str = (
        "Generates an image using Google's Imagen 3 model, saves it as an artifact, and returns the persistent S3 URL. "
        "Useful for creating visual assets when none exist."
    )
    args_schema: Type[BaseModel] = GenerateImagenInput

    def _run(self, prompt: str, crew_run_id: str) -> str:
        try:
            print(f"Generating image with Imagen 3 for prompt: {prompt[:50]}...")
            
            # Initialize Google Gen AI Client
            # NOTE: Ensure GOOGLE_API_KEY is set in your .env file
                
            client = genai.Client()
            
            # Generate image using Imagen 3
            response = client.models.generate_images(
                model='imagen-4.0-generate-001',
                prompt=prompt,
                config=types.GenerateImagesConfig(
                    number_of_images=1,
                    include_rai_reason=True,
                    output_mime_type="image/png"
                )
            )

            # Validate response
            if not response.generated_images:
                return "Error: No image generated by Google Gen AI (possibly blocked by safety filters)."
            first_candidate = response.generated_images[0]

            # 2. Check if the candidate actually contains an image object
            #    (This fixes the Pylance "OptionalMemberAccess" error)
            if not first_candidate.image:
                return "Error: Candidate returned but 'image' field is None."
            # Imagen returns raw image bytes directly, so we can skip the download step
            image_bytes = first_candidate.image.image_bytes
            if not image_bytes:
                return "Error: Generated image bytes are empty."
            base64_content = base64.b64encode(image_bytes).decode('utf-8')

            print(f"Saving Image Artifact for Run: {crew_run_id}...")
            
            crud_client = AuthenticatedClient(
                base_url=settings.CRUD_SERVICE_URL,
                token=settings.INTERNAL_CREW_API_KEY
            )

            safe_name = "".join(x for x in prompt[:20] if x.isalnum()) or "image"
            file_name = f"gen_{safe_name}_{UUID(crew_run_id).hex[:8]}.png"

            artifact_body = ArtifactServerCreate(
                type_=ArtifactType.IMAGE,
                file_name=file_name,
                file_content_base64=base64_content
            )

            create_result = create_artifact_artifact_crew_run_id_post.sync(
                crew_run_id=UUID(crew_run_id),
                client=crud_client,
                body=artifact_body
            )

            if isinstance(create_result, ArtifactRead):
                s3_url = get_artifact_artifact_artifact_id_get.sync(
                    artifact_id=create_result.id,
                    client=crud_client
                )
                return str(s3_url)
            
            return f"Error saving artifact: {create_result}"

        except Exception as e:
            return f"Error creating image: {str(e)}"

generate_imagen_tool = GenerateImagenTool()